### PR TITLE
fix: parameter persistence on layout

### LINKED ISSUE #217: Persistence of Parameters in Step 2
## Bug Report

Values entered in `step-2` do not get saved when the component unmounts.

### Current Behavior
The values entered in the different tabs of `step-2` (**Preprocessing Params**, **Model Layers**, and **Hyperparams**) are not saved unless clicked on any other tab (listed above). For example, after entering values in any tab if the user clicks on the Home icon, the values entered in the current tab are not persisted.

### Expected behavior/code
The entered values must be saved whenever the tab / component unmounts, rather than when another tab is clicked.

### PR DESCRIPTION
**Pull request by ShwetKhatri2001**
# Pull Request

## What does this PR do?
Fixes #217

The parameters for step-2 are persisting now wherever the user navigate using either inside tabs or outer layout links. 
For tabs inside step2, data was already being saved onchanging those tabs , now I am saving it on outer tab changes as well.

Find the Demo :

https://user-images.githubusercontent.com/56475750/153682251-93e6c698-8f07-4469-bece-dc4adf61e897.mp4

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

File: FrontEndApp/v1-react/src/Components/Login/LoginIndex.js [hunk 1]
```diff
@@ -1,25 +1,28 @@
...
 import Deployment from "../Deployment/DeploymentIndex";
 import Layout from "../MainApp/Layout";
-import step2 from "../MainApp/Step2";
+import Step2 from "../MainApp/Step2";
 import AuthorizeGitHub from "../MainApp/step-2/AuthorizeGithub.js";
 import GitHubResponse from "../MainApp/step-2/GitHubResponse";
 
 function LoginIndex() {
+  
+  const step2Ref = useRef();
```
Comment (McTechie) [inline FrontEndApp/v1-react/src/Components/Login/LoginIndex.js:14]:
```suggestion
  const step2Ref = useRef(null);
```

**Review by McTechie — CHANGES_REQUESTED** [review]
Just a minor change, everything else looks good to me xD

**Review by McTechie — APPROVED** [review]
